(function(g){var window=this;'use strict';var K3=function(a){a.ra("cardstatechange",a.Qk()&&a.fp()?1:0)},L3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Wmb=function(a){var b=g.ws(a);
a=g.zs(a);return new g.ks(b.x,b.y,a.width,a.height)},Xmb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.qC(a,b,function(){g.rC(e);c.apply(a,arguments)},d)},O3=function(a){a=g.fb(a);
delete M3[a];g.md(M3)&&N3&&N3.stop()},Zmb=function(){N3||(N3=new g.Tu(function(){Ymb()},20));
var a=N3;a.isActive()||a.start()},Ymb=function(){var a=g.kb();
g.bd(M3,function(b){$mb(b,a)});
g.md(M3)||Zmb()},P3=function(a,b,c,d){g.mv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},$mb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;anb(a,a.progress);1==a.progress?(a.j=0,O3(a),a.onFinish(),a.jr()):a.isPlaying()&&a.NL()},anb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},bnb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},Q3=function(a,b,c,d,e){P3.call(this,b,c,d,e);
this.element=a},cnb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Q3.call(this,a,b,c,d,e)},dnb=function(a){return Math.pow(a,3)},enb=function(a){return 3*a*a-2*a*a*a},fnb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},R3=function(a){return a.baseUrl||null},S3=function(a,b){return g.rt(g.Hr(a,b),function(c){return!!c})},gnb=function(a,b,c){function d(ta){var ka=ta.hovercardButton;
if(!ka)return null;ka=ka.subscribeButtonRenderer;if(!ka)return null;var wa=f(ka.unsubscribedButtonText),ea=f(ka.subscribedButtonText);if(ka.subscribed){var Y=f(ka.subscriberCountWithUnsubscribeText);var Na=f(ka.subscriberCountText)}else Y=f(ka.subscriberCountText),Na=f(ka.subscriberCountWithSubscribeText);var y=null;if(ta.signinEndpoint){y=L3(ta,"signinEndpoint","webNavigationEndpointData","url");if(!y){var ba,Ja;y=null==(Ja=g.U(null==(ba=ka.signInEndpoint)?void 0:ba.commandMetadata,g.F2))?void 0:
Ja.url}if(!y)return null}return wa&&(ea||y)?{subscribed:ka.subscribed,subscribeText:wa,subscribeCount:Y,unsubscribeText:ea,unsubscribeCount:Na,enabled:ka.enabled,signinUrl:y,classic:ta.useClassicSubscribeButton}:null}
function e(ta){if(ta){var ka=[],wa=ta.videoId;wa&&ka.push("v="+wa);(wa=ta.playlistId)&&ka.push("list="+wa);(ta=ta.startTimeSeconds)&&ka.push("t="+ta);return"/watch?"+ka.join("&")}}
function f(ta){if(!ta)return null;var ka=ta.simpleText;return ka?ka:ta.runs?g.Hr(ta.runs,function(wa){return wa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,E=null,F=null,G=null,L=null,Q=null;if("VIDEO"===h)g.U(l,g.aG)?m=g.U(l,g.aG).url:(Q=g.U(l,g.bT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.aG)?m=g.U(l,g.aG).url:(Q=g.U(l,g.bT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=L3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((F=L3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=L3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=L3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
aa="";if(b.metadata){var ma=f(b.metadata);ma&&(aa=ma)}return{id:"element-"+c,type:h,title:f(b.title),metadata:aa,callToAction:f(b.callToAction),wW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,pE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:E,isSubscribe:w,targetUrl:m||null,J8:n,sessionData:R?{itct:R}:null,jda:q,NC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:S3(b.impressionUrls||[],R3),w8:S3(b.hovercardShowUrls||[],R3),clickUrls:S3(l.loggingUrls||[],R3),visualElement:g.fF(b.trackingParams),productPrice:G,additionalFeesText:L,watchEndpoint:Q||null}},hnb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:S3(a.impressionUrls||[],R3),elements:S3(a.elements||[],function(d,e){return gnb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.fF(a.trackingParams));return c},inb=function(a){g.PV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.TR(a)||g.VR(a);this.events=new g.AK(this);g.N(this,this.events);this.events.T(this.player,g.MJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.NJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Xb);this.events.T(window,"focus",this.wba);this.load();var b=g.If("STYLE");(g.xf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},jnb=function(a){return a.player.getVideoData().Of?"current":a.Z?"new":"current"},T3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},knb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=hnb(f,jnb(a))));U3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.py;d&&(c.postParams={ad_tracking:d});if(b=g.jUa(b))if(b=g.ye(b),b=g.ke(b))a.C=g.IB(b,c)},U3=function(a,b,c){c=void 0===c?!0:c;
a.player.zf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&lnb(a);c=[];d=new g.LJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.iU(a.player,a.B.element,4),a.D=new g.tG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=mnb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.iU(a.player,f.element,4);var h=new g.LJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);nnb(a,f,e)}else g.lF(new g.HC("buildEndscreenElement null",
e))}a.player.tf(c);a.Xb()}},lnb=function(a){var b=g.gF(),c=g.hF();
c&&b&&a.endscreen.visualElement&&g.oB(g.uF)(void 0,c,b,a.endscreen.visualElement)},mnb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.NC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:V3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:W3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.rv(b.title||"")},ya:b.title},{I:"div",S:b.pE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.NC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:V3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:W3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.rv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.NC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],X:{href:W3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.rv(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:V3(b)}]};c=new g.V(c);var d=g.yf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.av(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.xW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.NC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.rv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],X:{href:W3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:V3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:onb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.NC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.rv(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:W3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:V3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.av(c.element,"ytp-ce-placeholder");return c},V3=function(a){if(a.wW)var b=a.wW.thumbnails;
return onb(b?b[b.length-1].url:null)},onb=function(a){return a?{style:"background-image: url("+a+")"}:{}},nnb=function(a,b,c){function d(m){m&&(b.Ua("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.av(b.element,"ytp-ce-force-expand"),X3(a,c.id,!0)):(g.cv(b.element,"ytp-ce-force-expand"),g.cv(b.element,"ytp-ce-element-hover"),X3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ua("mouseenter",function(){pnb(a,b,c)});
b.Ua("mouseleave",function(){qnb(a,b,c)});
a.player.U().B||b.Ua("click",function(){g.av(b.element,"ytp-ce-element-hover")});
b.Ua("click",function(m){rnb(a,c,m)});
b.Ua("keypress",function(m){rnb(a,c,m)});
b.Ua("focus",function(){pnb(a,b,c)});
b.Ua("blur",function(){qnb(a,b,c)});
b.Ua("touchstart",function(){pnb(a,b,c)});
var l=g.Af("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.cv(b.element,"ytp-ce-element-hover");g.cv(b.element,"ytp-ce-force-expand")});
b.Ua("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Af("ytp-sb-subscribe",b.element));d(g.Af("ytp-sb-unsubscribe",b.element));b.Ua("focus",f);b.Ua("blur",h)},rnb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.$u(d,"ytp-ce-element");){g.$u(d,"subscribe-label")&&snb(a,b);
if(g.$u(d,"ytp-ce-channel-subscribe"))return;d=g.Sf(d)}if(!d||g.$u(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])qnb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.jda)snb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ye(W3(a,b.targetUrl)),g.VG(g.ke(c),void 0,b.sessionData);else{var e=g.eS(a.player.U())||a.player.getVideoData().Of,f=function(){var h=W3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.tB(h);e&&n&&(n.v||
n.list)?a.player.Mo(n.v,l,n.list,!1,void 0,m||void 0):g.Wxa(h,l)};
snb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},W3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.lS(a)+b}else return"";return b},pnb=function(a,b,c){g.$u(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.av(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Tu(function(){g.av(b.element,"ytp-ce-element-hover")},200)).start():g.av(b.element,"ytp-ce-element-hover"),Y3(a,c.w8),X3(a,c.id,!0))},qnb=function(a,b,c){g.cv(b.element,"ytp-ce-element-hover");
g.cv(b.element,"ytp-ce-force-expand");X3(a,c.id,!1)},X3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.lv(a.j[e].element,"ytp-ce-element-shadow-show",c)},Y3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||T3(a))c&&c();else{b=tnb(a,b);var e=0,f=!1,h=new g.Tu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.aE(b[a],d)}},snb=function(a,b,c){Y3(a,b.clickUrls,c);
(a=g.hF())&&b.J8&&g.BF(a,b.visualElement)},tnb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(unb(b[d],c));return a},unb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},vnb=function(a){return"string"===typeof a?a:""},Z3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},wnb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},$3=function(a){return a.value?a.value:null},a4=function(a){if(!a)return null;
var b=g.ye(vnb(a.value));b=g.ke(b);if(!b)return null;var c=Z3(a.target,xnb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new wnb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},ynb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Bnb=function(a){if(!a)return null;
var b=Z3(a.type,znb),c=Z3(a.trigger,Anb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=a4(a?a:null);return b?new ynb(b,c,a):null},Cnb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Dnb=function(a,b){return g.Db(a.action,b)},Enb=function(a,b){this.context=a;
this.j=b},Fnb=function(a){return a.customMessage?b4("div","iv-card-message",a.customMessage):""},c4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Gnb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(b4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},b4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.rv(c);return{I:a,X:b,ya:c}},Hnb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.XC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.XC+");");c.dir=g.rv(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,X:c,V:d}},d4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.ij.click,5)}},Inb=function(a,b){this.merchant=a;
this.price=b},Jnb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Knb=function(a,b){return b?b:Jnb(a)?"current":"new"},e4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.ub=!1;this.Ya=new Map;this.fb=new Map;this.context.J.addEventListener(g.MJ("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.NJ("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},f4=function(a,b,c,d,e,f,h){a.context.j.Ua(b,"click",function(l){a.OL(c,d,e,f||[],h||0,l)});
a.context.j.Ua(b,"touchstart",function(){a.ub=!1});
a.context.j.Ua(b,"touchmove",function(){a.ub=!0})},Lnb=function(a){var b;
return(null==(b=g.U(a,g.aG))?0:b.url)?g.U(a,g.aG).url:(a=g.U(a,g.bT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},g4=function(a,b,c){return{bY:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
J0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
eL:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Mnb=function(a,b,c){e4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Oa=this.Ob=this.C=this.isInitialized=!1;this.cards=[];this.wb=this.Z=this.Na=this.G=this.Xa=this.j=null;this.oa=[];this.va=this.N=this.Lf=this.Fa=null;this.K=0;this.Ia=new g.Tu(function(){},c.W.Lk?4E3:3E3);
g.N(this,this.Ia);this.gb=new g.Tu(function(){});
g.N(this,this.gb);this.Ca=new Enb(c,function(e,f,h,l,m,n){f4(d,e,f,h,l,m,n)});
this.Y=new g.V({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.bb=new g.tG(this.Y,330);g.N(this,this.bb);this.Nb=g.Af("iv-drawer-header-text",this.D);this.B=g.Af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ob&&h4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ob=d.C)&&i4(d)});
this.Sa=new g.AK(this);g.N(this,this.Sa);this.J.addEventListener("videodatachange",this.kt.bind(this))},Nnb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){h4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){i4(a)});
var c=b.headerText;g.Uf(a.Nb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.fF(b.trackingParams);a.N=g.fF(b.closeTrackingParams);a.Lf=g.fF(b.iconTrackingParams)},Onb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.PF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,ij:{},ip:null,Oj:e.trackingParams?g.fF(e.trackingParams):null,Lf:f&&f.trackingParams?g.fF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
XC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};j4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.PF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:k4(a,c,b,f),sponsored:!1,ij:g4(f,e,f.command),ip:f.trackingParams?g.fF(f.trackingParams):null,Oj:e.trackingParams?g.fF(e.trackingParams):null,Lf:l&&l.trackingParams?g.fF(l.trackingParams):null,imageUrl:l4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.PF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,XC:null,title:f.title?g.PF(f.title):"",customMessage:f.callToAction?g.PF(f.callToAction):"",url:g.U(f.command,g.aG).url?a4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.aG).url}):null,onClickCommand:null};j4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.PF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:k4(a,c,b,e),sponsored:!1,ij:g4(e,f,e.endpoint),ip:e.trackingParams?g.fF(e.trackingParams):null,Oj:f.trackingParams?g.fF(f.trackingParams):null,Lf:l&&l.trackingParams?g.fF(l.trackingParams):null,channelId:g.U(e.endpoint,g.qT).browseId,customMessage:e.customText?g.PF(e.customText):null,profileImageUrl:l4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.PF(e.channelName):"",metaInfo:[e.subscriberCountText?g.PF(e.subscriberCountText):""],url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.qT).canonicalBaseUrl?g.U(e.endpoint,g.qT).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.qT).browseId}),onClickCommand:null};j4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.PF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:k4(a,c,b,e),sponsored:!1,ij:g4(e,f,e.action),ip:e.trackingParams?g.fF(e.trackingParams):null,Oj:f.trackingParams?g.fF(f.trackingParams):null,Lf:l&&l.trackingParams?g.fF(l.trackingParams):null,wG:l4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.PF(e.customMessage):null,playlistVideoCount:g.PF(e.playlistVideoCount),title:e.playlistTitle?g.PF(e.playlistTitle):"",metaInfo:[e.channelName?g.PF(e.channelName):
"",e.videoCountText?g.PF(e.videoCountText):""],url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Lnb(e.action)}),onClickCommand:null};j4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.PF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:k4(a,c,b,e),sponsored:!1,ij:g4(e,f,e.action),ip:e.trackingParams?g.fF(e.trackingParams):null,Oj:f.trackingParams?g.fF(f.trackingParams):null,Lf:l&&l.trackingParams?g.fF(l.trackingParams):null,wG:l4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.PF(e.lengthString):null,customMessage:e.customMessage?g.PF(e.customMessage):null,title:e.videoTitle?g.PF(e.videoTitle):"",metaInfo:[e.channelName?g.PF(e.channelName):
"",e.viewCountText?g.PF(e.viewCountText):""],isLiveNow:!!e.badge,url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Lnb(e.action)}),onClickCommand:null};j4(a,b)}}}}}a.K++},l4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},k4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Qnb=function(a,b){if(b=Pnb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Gf.id),g.Rf(b.jN),g.Hb(a.cards,b),a.qH(),m4(a)},h4=function(a,b,c){if(!a.C){a.bb.show();
a.Xa=new g.Tu(function(){g.av(a.context.J.getRootNode(),g.fZ.IV_DRAWER_OPEN)},0);
a.Xa.start();a.Sa.T(a.B,"mousewheel",function(h){a.Ia.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.hF();d&&a.Fa&&a.N&&g.zF(d,[a.Fa,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.UY||(f.UY=!0,Rnb(a.context.logger,f.Gf.ij.bY,b)),d&&g.zF(d,[f.Gf.ip]);K3(a.J);c&&(a.G=new g.Tu(function(){a.Na=a.Z;a.wb.focus()},330),a.G.start())}},i4=function(a){a.C&&(a.bb.hide(),g.wC(a.Sa),g.cv(a.context.J.getRootNode(),g.fZ.IV_DRAWER_OPEN),a.C=!1,K3(a.J),a.G&&a.G.stop(),a.G=new g.Tu(function(){a.Na&&(a.Na.focus(),a.Na=null)},330),a.G.start())},Tnb=function(a){g.bv(a.Kb(),
[g.fZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.iU(a.J,a.D,5);Snb(a);a.Z=g.Af("ytp-cards-button",a.J.getRootNode());a.wb=g.Af("iv-drawer-close-button",a.D);a.isInitialized=!0},Snb=function(a){var b=g.Af("iv-drawer-close-button",a.D);
a.context.j.Ua(b,"click",a.g6,a);a.context.j.Ua(a.B,"touchend",function(){a.Ia.start()});
a.context.j.Ua(a.B,"scroll",a.E6,a);a.context.B.subscribe("onHideControls",function(){a.Oa=!0});
a.context.B.subscribe("onShowControls",function(){a.Oa=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Oa=g.$u(a.J.getRootNode(),"ytp-autohide")});
a.oa.push(g.oE("iv-button-shown",a.b9,a));a.oa.push(g.oE("iv-button-hidden",a.a9,a));Unb(a)},Unb=function(a){a.oa.push(g.oE("iv-teaser-shown",a.K2,a));
a.oa.push(g.oE("iv-teaser-hidden",a.c9,a));a.oa.push(g.oE("iv-teaser-clicked",a.J2,a));a.Db=!0},Vnb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.sjb))?void 0:c.targetId)?(a.va=b,!0):!1},Wnb=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.ISa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.W0a))?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},j4=function(a,b){if(!Vnb(a,b)||Wnb(a,b)){var c=Xnb(a,b);
if(c){var d={Gf:b,jN:c.element,UY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||Unb(a),Qnb(a,b.id),c=a.findLastIndex(d),g.Rb(a.cards,c,0,d));else{a.isInitialized||Tnb(a);Qnb(a,b.id);var e=a.findLastIndex(d);g.Rb(a.cards,e,0,d);c.Ka(a.B,e);a.qH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,m4(a),Ynb(a,d),h4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Znb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Znb(a,d)}),m4(a))}}},Xnb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=Hnb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?$3(b.url)||"":""},V:[c4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[b4("h2",void 0,b.title),d]}]}]};c=new g.V(c);d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],X:{href:$3(b.url)||"","data-ytid":b.channelId},V:[c4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Fnb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},Gnb(b)]}]}]};c=new g.V(c);d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:$3(b.url)||""},V:[c4(b.wG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Fnb(b),b4("h2","iv-card-primary-link",b.title),Gnb(b)]}]}]};
c=new g.V(c);d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Hnb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?$3(b.url)||"":"";c={I:"div",Ma:c,X:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[b4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.If("span");g.Uf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Xd(d,"adInfo");d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:$3(c))||""},V:[c4(b.wG,d),{I:"div",S:"iv-card-content",V:[Fnb(b),b4("h2","iv-card-primary-link",b.title),Gnb(b),f]}]}]};c=new g.V(e);d4(a,g.zf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},$nb=function(a){if(a.j)return"productListing"===a.j.Gf.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Ir(a.cards,function(c){return"productListing"===c.Gf.type})}return g.Ir(a.cards,function(c){return"productListing"===c.Gf.type})},m4=function(a){g.lv(a.J.getRootNode(),"ytp-cards-shopping-active",$nb(a))},Znb=function(a,b){if(!g.$u(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.hF(),d=a.j?a.j.Gf.Lf:a.Lf;
c&&d&&g.AF(c,[d]);a.j=b;m4(a)}(c=a.isInitialized&&"none"==a.Kb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.Gf.teaserDurationMs&&a.J.sB(!0,{teaserText:b.Gf.teaserText,durationMs:b.Gf.teaserDurationMs,onClickCommand:b.Gf.onClickCommand});a.gb.isActive()||((!a.C||!a.Ia.isActive()&&a.Oa)&&Ynb(a,b),a.gb.start(910+b.Gf.teaserDurationMs))}},Ynb=function(a,b){a.Y.Gb?(b=new P3([0,
a.B.scrollTop],[0,b.jN.offsetTop],600,enb),a.context.C.Ua(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ua(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.LF(a.Y,!0),a.B.scrollTop=b.jN.offsetTop,g.LF(a.Y,!1))},n4=function(a){return a.j&&a.j.Gf?a.j.Gf:a.cards[0]&&a.cards[0].Gf?a.cards[0].Gf:null},Pnb=function(a,b){return g.Db(a.cards,function(c){return c.Gf.id===b})},o4=function(a,b,c){e4.call(this,a,b);
this.annotation=c;this.isActive=!1},aob=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},p4=function(a,b,c){o4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},bob=function(a,b){var c=void 0===c?0:c;
var d=Wmb(b).width;g.us(b,d);c=new cnb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,dnb);g.N(a,c);a.context.C.Ua(c,"begin",function(){g.As(b,!0)});
c.play()},eob=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.xW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ka(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.As(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.ns(l,"right",b.image_width+"px");g.Kf(a.Kb(),l);a.C=new g.Tu(function(){cob(a,h,l)},500);
g.N(a,a.C);a.context.j.Ua(a.Kb(),"mouseover",function(){dob(a,h,l,f,b.image_height)});
a.context.j.Ua(a.Kb(),"mouseout",function(){a.C.start()})}},dob=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.zs(b);a.j||(b.style.width=g.ts(f.width,!0),c.style.width=g.ts(f.width,!0));g.ns(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ns(d,"right","1px");a.D=!0;g.As(b,!0);a.G=new g.Tu(function(){g.av(this.Kb(),"iv-branding-active")},0,a);
a.G.start()}},cob=function(a,b,c){g.cv(a.Kb(),"iv-branding-active");
a.K=new g.Tu(function(){g.As(b,!1);a.j||(c.style.width=g.ts(0,!0))},250);
a.K.start();a.D=!1},fob=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},gob=function(a,b,c){o4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Tu(function(){d.j.setAttribute("aria-hidden","true");g.As(d.C,!1);g.As(d.B,!0)},700,this);
g.N(this,this.G)},job=function(a,b,c){c.stopPropagation();
hob(a);iob(a,b);a.j.focus()},kob=function(a){a.isCollapsed||a.Z||a.D||(g.av(a.Kb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},hob=function(a){a.G.stop();
a.isCollapsed&&(g.dv(a.Kb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.As(a.B,!1),g.As(a.C,!0))},iob=function(a,b){a.D||(a.D=g.yg(function(){lob(this);
kob(this)},b,a))},lob=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},mob=function(a){this.J=a},Rnb=function(a,b,c){b&&(c?q4(a,b.map(function(d){return g.Iu(d,c)})):q4(a,b))},q4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.aE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},nob=function(a){g.PV.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new mob(this.player);this.D=new g.AK(this);this.G=this.K=null;this.events=new g.AK(this);this.Yg=this.Y=this.j=null;this.va=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ra("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.L2,this);this.subscribe("resize",this.UJ,this);this.player.U().Oa.subscribe("vast_info_card_add",this.XZ,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.iU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",Ma:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.ju()&&this.load();var c=this.createElement({I:"style"});(g.xf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},oob=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.As(a,!1);return a},pob=function(a,b){b=!b.isCued()&&!g.AG(b,1024);
g.LF(a.B,b);g.LF(a.C,b)},qob=function(a,b,c){a.Z=!0;
a.G=g.IB(b,c)},rob=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(rob(a,e))}return c},vob=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.BB(h)&&h.responseXML?h.responseXML:null)&&sob(a,h)}};
g.PC()&&(d.onFinish=tob(a,d.onFinish));d.postParams={ic_only:"1"};uob(d,c);a.Z=!0;g.IB(b.Xa,d)}}},uob=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.vH&&(a.postParams.ic_coll=b.vH);b.kN&&(a.postParams.ic_xml=b.kN);b.jL&&(a.postParams.ic_track=b.jL)},wob=function(a){var b=new g.V({I:"div"});
g.As(b.element,!1);var c=new Mnb(a.player,b.element,r4(a));g.N(c,b);b.Ka(a.B.element);c.fG();return c},yob=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.oa=!0,xob(a,b),b.headerText&&a.Yg&&(c=g.PF(b.headerText),a.Yg.setAttribute("title",c))},r4=function(a){if(!a.Y){var b=new fnb(a);
g.N(a,b);var c=new g.Hp(a);g.N(a,c);a.Y=new fob(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.xj)}return a.Y},sob=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.hF();if(e){var f=g.gF();f&&g.oB(g.uwa)(void 0,e,f,[g.fF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=rob(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Z3(f.type,zob),p=Z3(f.style,Aob),q=vnb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Bnb;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var E=f(A.value);
E&&l.push(E)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Cnb(m,n,p,v,r):null}else e=null}catch(ma){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=oob(f),L=null;switch(l.type){case "branding":if(f.player.U().oe)break;f.B.element.appendChild(G);L=new p4(G,r4(f),l);break;case "promotion":g.iU(f.player,G,4),L=new gob(G,r4(f),l)}L&&L.fG();if(f=L)g.N(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=wob(a),g.N(a,a.j));if("card"===e.type){G=a.j;var Q=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(Q)switch(f=e.tracking||{},f={bY:f.impression,click:f.click,close:f.close,J0:f.teaser_impression,eL:f.teaser_click},l=e.tracking_params||{},L=null,Q){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ij:f,ip:l.card?g.fF(l.card):null,Oj:l.teaser?g.fF(l.teaser):null,Lf:l.icon?g.fF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};j4(G,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ij:f,
ip:l.card?g.fF(l.card):null,Oj:l.teaser?g.fF(l.teaser):null,Lf:l.icon?g.fF(l.icon):null,wG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};j4(G,c);break;case "productListing":e.signin_url&&(L=a4({target:"current",value:e.signin_url}));Q=[];for(var R=e.offers||[],aa=0;aa<R.length;aa++)Q.push(new Inb(g.gf(R[aa].merchant),
g.gf(R[aa].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ij:f,ip:l.card?g.fF(l.card):null,Oj:l.teaser?g.fF(l.teaser):null,Lf:l.icon?g.fF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,XC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),ppb:L,opb:e.signin_title?e.signin_title:void 0,npb:e.signin_message?e.signin_message:void 0,offers:Q,onClickCommand:null};j4(G,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ij:f,ip:l.card?g.fF(l.card):
null,Oj:l.teaser?g.fF(l.teaser):null,Lf:l.icon?g.fF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,XC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};j4(G,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ij:f,ip:l.card?g.fF(l.card):null,Oj:l.teaser?g.fF(l.teaser):null,Lf:l.icon?g.fF(l.icon):null,wG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},j4(G,c)}}else Nnb(a.j,e);c=!0}}c&&
(K3(a.player),a.UJ())},xob=function(a,b){var c=!1;
a.j||(a.j=wob(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Onb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.xT(f)||(c=a.j,d=b.headerText?g.PF(b.headerText):"",g.Uf(c.Nb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.fF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.fF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Lf=b.icon.infoCardIconRenderer.trackingParams?g.fF(b.icon.infoCardIconRenderer.trackingParams):null,a.UJ());K3(a.player)}},Bob=function(a,b,c,d,e){if(!a.player.U().oe){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.qT)&&g.U(b.navigationEndpoint,g.qT).browseId&&f.push(new ynb("openUrl","click",new wnb("/channel/"+g.U(b.navigationEndpoint,g.qT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.rT)){d.channel_id=g.U(b.subscribeButton,g.rT).channelId;var l;b=g.U(b.subscribeButton,g.rT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.PF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.PF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.PF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.PF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.F2))?void 0:m.url)||"";l={subscribeText:g.PF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.PF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Cnb(c,"branding","branding",f,d);l=oob(a);a.B.element.appendChild(l);f=new p4(l,r4(a),f);f.fG();g.N(f,f);a.N[c]=f}},tob=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.va.push(g.Lu.Ri(function(){b.apply(null,g.pa(c))}))}},Cob=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.bU.prototype.sB=g.fa(29,function(a,b){var c=g.fW(this.Ab());c&&c.sB(a,b)});
var M3={},N3=null;g.ob(P3,g.mv);g.k=P3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;O3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.LJ();this.jm("play");this.isPaused()&&this.jm("resume");this.j=1;var b=g.fb(this);b in M3||(M3[b]=this);Zmb();$mb(this,a);return!0};
g.k.stop=function(a){O3(this);this.j=0;a&&(this.progress=1);anb(this,this.progress);this.jm("stop");this.jr()};
g.k.pause=function(){this.isPlaying()&&(O3(this),this.j=-1,this.jm("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.jm("destroy");P3.Uf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.NL=function(){this.jm("animate")};
g.k.jm=function(a){this.dispatchEvent(new bnb(a,this))};
g.ob(bnb,g.Ab);g.ob(Q3,P3);Q3.prototype.C=function(){};
Q3.prototype.NL=function(){this.C();Q3.Uf.NL.call(this)};
Q3.prototype.jr=function(){this.C();Q3.Uf.jr.call(this)};
Q3.prototype.LJ=function(){this.C();Q3.Uf.LJ.call(this)};
g.ob(cnb,Q3);cnb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(fnb,g.I);g.k=fnb.prototype;g.k.Ua=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.qC(a,b,c);this.j.push(a);return a};
g.k.mJ=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=Xmb(a,b,c);this.j.push(a);return a};
g.k.Uc=function(a){g.rC(a);g.Hb(this.j,a)};
g.k.Tf=function(){g.rC(this.j);this.j.length=0};
g.k.xa=function(){this.Tf();g.I.prototype.xa.call(this)};g.x(inb,g.PV);g.k=inb.prototype;g.k.load=function(){g.PV.prototype.load.call(this);if(!T3(this)){var a=g.kUa(this.player.getVideoData());a?(a=hnb(a,jnb(this)),U3(this,a,!1)):knb(this)}};
g.k.unload=function(){U3(this,null);this.C&&(this.C.abort(),this.C=null);g.PV.prototype.unload.call(this)};
g.k.Ph=function(a,b){return T3(this)?"loadCustomEndscreenRenderer"===a?(a=hnb(b,"new"),U3(this,a),!0):null:null};
g.k.getOptions=function(){return T3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Dob.length;f++){var h=Math.abs(b.width-Dob[f]);if(-1===e||d>=h)e=f,d=h}d=Eob[e];this.B&&g.ns(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.ys(e.element,m,f);g.us(e.element,n,p);g.dv(e.element,Fob);256<m||256<f?g.av(e.element,"ytp-ce-large-round"):96<m||96<f?g.av(e.element,"ytp-ce-medium-round"):g.av(e.element,"ytp-ce-small-round");g.dv(e.element,Gob);m=h.left+h.width/2;h=h.top+l/2;g.av(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.dv(e.element,Eob);g.av(e.element,d);(e=g.yf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ns(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())Y3(this,this.endscreen.impressionUrls),(a=g.hF())&&this.endscreen.visualElement&&g.yF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.av(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.av(b,"ytp-ce-shown");Y3(this,c.impressionUrls);(b=g.hF())&&g.yF(b,c.visualElement);this.player.U().N&&this.player.qb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.cv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.cv(b,"ytp-ce-shown");this.player.U().N&&this.player.qb("endscreenelementhidden",a)}};
g.k.wba=function(a){var b=this;a.target===window&&(new g.Tu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.dv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Dob=[346,426,470,506,570,640,853,1280,1920],Eob="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Gob=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Fob=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var xnb={ava:"current",WVa:"new"};var znb={CLOSE:"close",NZa:"openUrl",SUBSCRIBE:"subscribe"},Anb={jta:"click",CLOSE:"close",aHa:"hidden",P4a:"rollOut",Q4a:"rollOver",F6a:"shown"};Cnb.prototype.Se=function(){var a=Dnb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Aob={Ena:"anchored",Y1:"branding",CHANNEL:"channel",Qua:"cta",dHa:"highlightText",eLa:"label",PLAYLIST:"playlist",x1a:"popup",F9a:"speech",SUBSCRIBE:"subscribe",vcb:"title",VIDEO:"video",Xjb:"website"},zob={Y1:"branding",Nqa:"card",bxa:"drawer",cHa:"highlight",qRa:"marker",c3a:"promotion",TEXT:"text",Elb:"widget"};g.x(e4,g.I);g.k=e4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.LJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.fb.set(a,e);this.context.J.tf([a])};
g.k.fG=function(){this.context.B.subscribe("resize",this.qH,this)};
g.k.Kb=function(){return this.element};
g.k.OL=function(a,b,c,d,e,f){if(this.ub)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Rf(this.Kb())};
g.k.qH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=$3(a);if(f){var h=Knb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Of||!1,n=g.tB(f||"");m&&n&&(n.v||n.list)?e.context.J.Mo(n.v,b,n.list,!1):g.VG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);q4(this.context.logger,c,l,d);Jnb(f)||(c=g.hF(),d=b.itct,c&&d&&g.BF(c,g.fF(d)))}};
g.k.xa=function(){this.Ya.clear();this.fb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.N(this,a);return a.element};g.x(Mnb,e4);g.k=Mnb.prototype;g.k.kt=function(){this.va&&j4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.zs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.qH=function(){var a=this.isAvailable();g.As(this.Kb(),a);g.lv(this.context.J.getRootNode(),g.fZ.IV_DRAWER_ENABLED,a);K3(this.J)};
g.k.destroy=function(){this.J.sB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.pE(this.oa);g.wC(this.Sa);this.Xa&&this.Xa.dispose();this.G&&this.G.dispose();e4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.Gf.startMs>c.Gf.startMs||a.Gf.startMs===c.Gf.startMs&&a.Gf.timestamp>=c.Gf.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.g6=function(){if(this.C){q4(this.context.logger,n4(this).ij.close);var a=g.hF();a&&this.N&&g.BF(a,this.N);i4(this)}};
g.k.E6=function(){g.lv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.b9=function(){var a=g.hF(),b=n4(this);b=b?b.Lf:this.Lf;a&&b&&g.zF(a,[b])};
g.k.a9=function(){var a=g.hF(),b=n4(this);b=b?b.Lf:this.Lf;a&&b&&g.AF(a,[b])};
g.k.K2=function(){var a=n4(this);q4(this.context.logger,a.ij.J0);var b=g.hF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Oj&&c.push(a.Oj);a.Lf&&c.push(a.Lf);0<c.length&&g.zF(b,c)}else g.zF(b,[a.Oj,a.Lf])};
g.k.c9=function(){var a=g.hF(),b=n4(this);a&&b&&g.AF(a,[b.Oj])};
g.k.J2=function(a){var b=n4(this),c=g.hF();this.j?a?(a=this.context.logger,q4(a,b.ij.eL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Oj&&g.BF(c,b.Oj)):(a=this.context.logger,q4(a,b.ij.eL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Lf&&g.BF(c,b.Lf)):(a=this.context.logger,q4(a,b.ij.eL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Lf&&g.BF(c,this.Lf))};g.x(o4,e4);o4.prototype.fG=function(){e4.prototype.fG.call(this);aob(this)};
o4.prototype.show=function(){e4.prototype.show.call(this);var a=g.hF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zF(a,[g.fF(b.itct)])};
o4.prototype.hide=function(){e4.prototype.hide.call(this);var a=g.hF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.AF(a,[g.fF(b.itct)])};g.x(p4,o4);p4.prototype.ox=function(){g.av(this.Kb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.As(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Kb().appendChild(b);var c=this.annotation.Se();c&&f4(this,b,c,this.annotation.id,a.session_data);eob(this,a)};
p4.prototype.show=function(){if(!this.isActive&&(o4.prototype.show.call(this),this.N||(this.ox(),this.N=!0),g.As(this.Kb(),!0),this.isActive=!0,this.B)){try{bob(this,this.B)}catch(a){}g.av(this.context.J.getRootNode(),"ytp-branding-shown")}};
p4.prototype.hide=function(){this.isActive&&(o4.prototype.hide.call(this),g.As(this.Kb(),!1),this.isActive=!1,g.cv(this.context.J.getRootNode(),"ytp-branding-shown"))};
p4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);o4.prototype.destroy.call(this)};g.x(gob,o4);g.k=gob.prototype;
g.k.ox=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Kb().setAttribute("aria-hidden","true");this.Kb().setAttribute("aria-label","Promotion");this.Kb().tabIndex=0;var e=this.annotation.Se(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&f4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Se(f,$3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&f4(this,
this.Kb(),e,this.annotation.id,b.session_data,void 0,c)}g.av(this.j,"iv-click-target");e&&f4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.av(this.j,"iv-click-target"),e&&f4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ua(this.B,"click",function(q){job(a,5E3,q)});
c.appendChild(this.B);g.As(this.B,!1);this.context.j.Ua(this.Kb(),"mouseover",this.X7,this);this.context.j.Ua(this.Kb(),"mouseout",this.W7,this);this.context.j.Ua(this.Kb(),"touchend",function(q){job(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ua(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.S7:this.R7,this);c.appendChild(this.C);g.bv(this.Kb(),d);h&&(g.Kf(this.Kb(),h),n&&h.appendChild(n));g.Kf(this.Kb(),this.N);g.Kf(this.Kb(),c)};
g.k.show=function(){this.isActive||(o4.prototype.show.call(this),this.Y||(this.ox(),this.Y=!0),g.As(this.Kb(),!0),g.yg(function(){g.cv(this.Kb(),"iv-promo-inactive")},100,this),this.Kb().removeAttribute("aria-hidden"),this.isActive=!0,lob(this),hob(this),iob(this,this.K))};
g.k.hide=function(){this.isActive&&(g.av(this.Kb(),"iv-promo-inactive"),this.isActive=!1,this.Kb().setAttribute("aria-hidden","true"))};
g.k.OL=function(a,b,c,d,e,f){return this.isCollapsed?!1:o4.prototype.OL.call(this,a,b,c,d,e,f)};
g.k.X7=function(a){this.Z=!0;job(this,500,a)};
g.k.W7=function(){this.Z=!1;kob(this)};
g.k.R7=function(a){a.stopPropagation();this.hide()};
g.k.S7=function(a){a.stopPropagation();lob(this);this.isCollapsed=!0;g.av(this.Kb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();o4.prototype.destroy.call(this)};g.x(nob,g.PV);g.k=nob.prototype;g.k.Ph=function(a,b){if(!Cob(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.l2(b))&&sob(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Qnb(this.j,b),K3(this.player)),!0}return null};
g.k.getOptions=function(){return Cob(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.ju=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.KT(b)||g.UT(this.player.app)?!1:1===c&&!b.pV||a.Oa.get(b.videoId)||g.yT(b)||g.lUa(b)?!0:!1};
g.k.UJ=function(){if(this.C){var a=this.player.rb().getVideoContentRect(!0);g.ys(this.C.element,a.width,a.height);g.us(this.C.element,a.left,a.top)}if(this.j){var b=this.player.En();a=this.j;b=b.width;g.lv(a.D,"iv-drawer-small",426>=b);g.lv(a.D,"iv-drawer-big",1280<=b)}};
g.k.L2=function(a){pob(this,a.state);g.AG(a.state,2)&&(this.Qk()&&this.fp()&&2!==this.player.getPresentingPlayerType()&&this.tB(!1),this.sB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.BB(h)&&h.responseXML?h.responseXML:null)&&(sob(b,h),g.av(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.PV.prototype.load.call(this);pob(this,this.player.Vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.PC()&&(a=tob(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Oa.get(d);f&&uob(e,f);f=f&&(f.kN||f.vH);if(!c.Iu||f)c.Xa?qob(this,c.Xa,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.xT(h))&&!b.oa&&yob(b,h)},this.player.addEventListener("videodatachange",this.K));
g.iU(this.player,this.C.element,4);this.UJ();(f=g.yT(c))&&xob(this,f);(f=g.lUa(c))&&f.featuredChannel&&Bob(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Yg=g.Af("ytp-cards-button",this.player.getRootNode());g.xT(c)&&yob(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&qob(this,b.Xa,a)};
g.k.unload=function(){this.player.zf("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,K3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.N={};this.B.hide();g.PV.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.XZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?vob(this):this.load())};
g.k.Qk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.oa};
g.k.fp=function(){return!!this.j&&this.j.C};
g.k.tB=function(a,b,c){b=void 0===b?!1:b;this.Qk();this.j&&(a?c?h4(this.j,c,b):h4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):i4(this.j))};
g.k.sB=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Oa.unsubscribe("vast_info_card_add",this.XZ,this);g.cv(this.player.getRootNode(),g.fZ.IV_DRAWER_OPEN);for(var a=this.va,b=g.Lu,c=0,d=a.length;c<d;c++)b.Uj(a[c]);this.va.length=0;g.PV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.N(this,a);return a.element};g.OV("annotations_module",nob);g.OV("creatorendscreen",inb);})(_yt_player);
